# specify the language and which version
language: python
python:
  - 2.7
  - 3.4
# setup miniconda
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7 ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  - conda info -a

  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

# command to install dependencies
install:
  # standard stuff you need for scientific computing
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas enum34 ipython matplotlib nose pandas numpy scipy sympy
  - conda install --yes -c http://conda.anaconda.org/bioconda python-libsbml graphviz
  - conda install --yes -c http://conda.anaconda.org/anaconda python-dateutil
  - python setup.py install
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script: python setup.py test
