name: pygom

on:
  push:
    branches:
      - master
      - release/*
      - feature/*
      - bugfix/*
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check python version and install dependencies
        run: python -c "import sys; print(sys.version)"
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install codecov
          
      - name: Build and install package for c files
        run: |
          python setup.py build
          python setup.py install
          pwd
          ls -lh
          echo "backend: TkAgg" >> ~/.matplotlib/matplotlibrc
          
      - name: Test and coverage
        run: coverage run setup.py test
